// Generates src/generated/skills.ts from the plugin/skills/<name>/SKILL.md files.
//
// The SKILL.md files are the single source of truth: Claude Code reads them
// directly as plugin skills, and this script compiles them into typed TS so
// library consumers (the Val Town app, the MCP server) never touch the
// filesystem at runtime.
//
// It doubles as the cross-consumer validation gate — every skill must satisfy
// both our schema AND Claude Code's frontmatter constraints, or the build fails.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SKILLS_DIR = join(ROOT, "plugin", "skills");
const OUT_FILE = join(ROOT, "src", "generated", "skills.ts");

const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/;
// Claude Code skill names: lowercase letters, numbers, hyphens; max 64 chars.
const NAME_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const MAX_NAME = 64;
// Claude Code budgets name + description together at ~1536 chars. Stay well under.
const MAX_DESCRIPTION = 1024;

/** @type {string[]} */
const errors = [];

/** @param {string} dir */
function parseSkill(dir) {
  const file = join(SKILLS_DIR, dir, "SKILL.md");
  if (!existsSync(file)) {
    errors.push(`${dir}: missing SKILL.md`);
    return null;
  }

  const match = readFileSync(file, "utf8").match(FRONTMATTER_RE);
  if (!match) {
    errors.push(`${dir}: missing YAML frontmatter (--- ... ---)`);
    return null;
  }

  const [, frontmatterRaw, body] = match;
  let fm;
  try {
    fm = parse(frontmatterRaw);
  } catch (err) {
    errors.push(`${dir}: invalid YAML frontmatter: ${err.message}`);
    return null;
  }

  const { name, description, triggers } = fm ?? {};

  if (typeof name !== "string" || name.length === 0) {
    errors.push(`${dir}: "name" is required`);
  } else {
    if (!NAME_RE.test(name)) {
      errors.push(
        `${dir}: name "${name}" must be lowercase letters, numbers, and hyphens`,
      );
    }
    if (name.length > MAX_NAME) {
      errors.push(`${dir}: name "${name}" exceeds ${MAX_NAME} characters`);
    }
    if (name !== dir) {
      errors.push(`${dir}: name "${name}" must match its directory name`);
    }
  }

  if (typeof description !== "string" || description.length === 0) {
    errors.push(`${dir}: "description" is required`);
  } else if (description.length > MAX_DESCRIPTION) {
    errors.push(
      `${dir}: description is ${description.length} chars (max ${MAX_DESCRIPTION})`,
    );
  }

  let trig = [];
  if (triggers !== undefined) {
    if (
      !Array.isArray(triggers) ||
      triggers.some((t) => typeof t !== "string")
    ) {
      errors.push(`${dir}: "triggers" must be an array of strings`);
    } else {
      trig = triggers;
    }
  }

  return {
    name: String(name),
    description: String(description),
    triggers: trig,
    body: body.trim(),
  };
}

const dirs = readdirSync(SKILLS_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

const skills = [];
const seen = new Set();
for (const dir of dirs) {
  const skill = parseSkill(dir);
  if (!skill) continue;
  if (seen.has(skill.name))
    errors.push(`${dir}: duplicate skill name "${skill.name}"`);
  seen.add(skill.name);
  skills.push(skill);
}

if (errors.length > 0) {
  console.error(
    `\n✗ Skill validation failed:\n${errors.map((e) => `  - ${e}`).join("\n")}\n`,
  );
  process.exit(1);
}

const entries = skills
  .map(
    (s) =>
      `  ${JSON.stringify(s.name)}: {\n` +
      `    name: ${JSON.stringify(s.name)},\n` +
      `    description: ${JSON.stringify(s.description)},\n` +
      `    triggers: ${JSON.stringify(s.triggers)},\n` +
      `    body: ${JSON.stringify(s.body)},\n` +
      `  },`,
  )
  .join("\n");

const out = `// AUTO-GENERATED by scripts/build.mjs — do not edit.
// Source of truth: plugin/skills/<name>/SKILL.md
import type { Skill } from "../types.js";

export const skills: Record<string, Skill> = {
${entries}
};

export const skillList: Skill[] = Object.values(skills);
`;

// The output dir is gitignored, so it won't exist in a fresh clone (e.g. when
// the package is installed as a git dependency and built via `prepare`).
mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, out);
console.log(`✓ Generated ${skills.length} skills -> src/generated/skills.ts`);
